// Colors palette generated by coolors https://coolors.co/121212-ffffff-7748ff-27273b
const SMOKY_BLACK = '#121212'
const WHITE = '#FFFFFF'
const MEDIUM_SLATE_BLUE = '#7748FF'
const SPACE_CADET = '#27273B'

const common = {
  BUTTON_BACKGROUND: MEDIUM_SLATE_BLUE,
  BUTTON_BORDER_COLOR: MEDIUM_SLATE_BLUE,
  BUTTON_TEXT_COLOR: WHITE,
}

const light = {
  ...common,
  BACKGROUND: WHITE,
  TEXT: SMOKY_BLACK,
}

const dark = {
  ...common,
  BACKGROUND: SPACE_CADET,
  TEXT: WHITE,
}

export const colors = {
  light,
  dark,
}

export type Colors = {
  colors: {
    BACKGROUND: string
    TEXT: string
    BUTTON_BACKGROUND: string
    BUTTON_BORDER_COLOR: string
    BUTTON_TEXT_COLOR: string
  }
}
